name: Solaris
on: [push, pull_request]

jobs:
  solaris:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout PPP sources
      uses: actions/checkout@v4
    - name: Build
      uses: vmactions/solaris-vm@v1.0.2
      with:
        release: "11.4-gcc"
        run: |
          ./autogen.sh CFLAGS="-Wno-deprecated-declarations"
          make
          make install
