name: Solaris
on: [push, pull_request]

jobs:
  solaris:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout PPP sources
      uses: actions/checkout@v3
    - name: Build
      uses: vmactions/solaris-vm@v1.0.0
      with:
        run: |
          pkg update
          pkg install gcc automake autoconf libtool
          ./autogen.sh CFLAGS="-Wno-deprecated-declarations"
          make
          make install
